import { QueryClient, QueryClientProvider, useQuery } from "@tanstack/react-query";
import { AnimatePresence, motion } from "framer-motion";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { ChevronRight, Filter, Focus, Gauge, Layers3, Maximize2, Pause, Play, RotateCcw, Search, Settings, Table2, VolumeX, X } from "lucide-react";
import { Component, lazy, Suspense, useEffect, useMemo, useState, type ReactNode } from "react";
import { dominance, formatMarketCap, performance, selectUniverse } from "../../features/market-war/calculations";
import { getProvider, MockMarketDataProvider } from "../../features/market-war/providers";
import type { CompanyMarketData, TimeRange } from "../../features/market-war/types";
import { useMarketWarStore } from "../../stores/marketWarStore";

const MarketWarScene=lazy(()=>import("./MarketWarScene").then(m=>({default:m.MarketWarScene})));
const queryClient=new QueryClient({defaultOptions:{queries:{staleTime:55_000,retry:2,refetchInterval:60_000}}});
const provider=getProvider();

class SceneBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<WebGLFallback/>:this.props.children}}
function WebGLFallback(){return <div className="webgl-fallback"><Layers3/><h2>3D view unavailable</h2><p>Your market data is still available in the rankings and accessible table.</p></div>}
const changeClass=(n:number)=>n>=0?"gain":"loss";
const icon:Record<string,string>={tank:"◉",aircraft:"✦",ship:"◆",drone:"⌘",armored_vehicle:"▣",command_center:"⬢"};

function MarketSummary({data}:{data:ReturnType<typeof dominance>}){return <section className="summary glass" aria-label={`Selected universe: USA ${data.usaPercent.toFixed(1)} percent, China ${data.chinaPercent.toFixed(1)} percent`}>
  <div className="country-score usa"><span><i/>USA</span><strong>{data.usaPercent.toFixed(1)}%</strong><small>{formatMarketCap(data.usa)}</small></div>
  <div className="dominance"><div className="bar"><motion.div animate={{width:`${data.usaPercent}%`}} transition={{type:"spring",damping:28}}/><span style={{left:`${data.usaPercent}%`}}/></div><small>{formatMarketCap(data.total)} selected public value</small></div>
  <div className="country-score china"><span>CHINA<i/></span><strong>{data.chinaPercent.toFixed(1)}%</strong><small>{formatMarketCap(data.china)}</small></div>
</section>}
function RangeControl(){const {range,set}=useMarketWarStore();return <div className="segmented" aria-label="Performance period">{(["24H","7D","1M","1Y"] as TimeRange[]).map(r=><button className={r===range?"active":""} onClick={()=>set("range",r)} key={r}>{r}</button>)}</div>}
function Header({data}:{data:ReturnType<typeof dominance>}){const {count,set}=useMarketWarStore();return <header className="war-header">
 <div className="brand"><div className="brand-mark"><span>★</span><span>★</span></div><div><h1>USA <em>vs</em> CHINA</h1><p>The Market Cap Frontline</p></div></div>
 <MarketSummary data={data}/>
 <div className="header-tools"><div className="status"><span/>DEMO DATA<small>Updated moments ago</small></div><RangeControl/><select value={count} onChange={e=>set("count",e.target.value==="all"?"all":Number(e.target.value) as 10)} aria-label="Company universe"><option value="10">Top 10</option><option value="25">Top 25</option><option value="50">Top 50</option><option value="100">Top 100</option><option value="all">All</option></select><button aria-label="Open settings" onClick={()=>set("settingsOpen",true)}><Settings/></button><button aria-label="Fullscreen" onClick={()=>document.documentElement.requestFullscreen?.()}><Maximize2/></button></div>
 </header>}
function Rankings({companies}:{companies:CompanyMarketData[]}){const {range,set}=useMarketWarStore();return <aside className="rankings glass"><div className="panel-title"><div><small>LEADING FORCES</small><h2>Market leaders</h2></div><Gauge/></div><div className="rank-columns">{(["USA","CHINA"] as const).map(country=><div key={country}><h3 className={country.toLowerCase()}><i/>{country}</h3>{companies.filter(c=>c.country===country&&c.status==="public").slice(0,5).map((c,i)=><button className="rank-row" key={c.id} onClick={()=>set("selectedId",c.id)}><span className="rank-num">{String(i+1).padStart(2,"0")}</span><span className="unit-icon">{icon[c.unitType]}</span><span className="rank-name"><b>{c.name}</b><small>{formatMarketCap(c.marketCapUsd)}</small></span><span className={changeClass(performance(c,range))}>{performance(c,range)>=0?"+":""}{performance(c,range).toFixed(1)}%</span><ChevronRight/></button>)}</div>)}</div></aside>}
function Legend(){return <aside className="legend glass"><small>HOW TO READ THE FIELD</small><div><span>◉</span><b>Unit size</b><em>Market cap</em></div><div><span>⇢</span><b>Movement</b><em>Performance</em></div><div><span>│</span><b>Frontline</b><em>Dominance</em></div><div><span>≈</span><b>Smoke / glow</b><em>Loss / gain</em></div><p>Striped units are private and excluded from totals.</p></aside>}
function FiltersPanel({sectors}:{sectors:string[]}){const s=useMarketWarStore();return <AnimatePresence>{s.filtersOpen&&<motion.aside className="drawer filters glass" initial={{x:-420}} animate={{x:0}} exit={{x:-420}}><div className="drawer-head"><div><small>FIELD CONTROL</small><h2>Filters</h2></div><button onClick={()=>s.set("filtersOpen",false)} aria-label="Close filters"><X/></button></div><label className="search"><Search/><input value={s.search} onChange={e=>s.set("search",e.target.value)} placeholder="Search company or ticker"/></label><label>Country<select value={s.country} onChange={e=>s.set("country",e.target.value as any)}><option>ALL</option><option>USA</option><option>CHINA</option></select></label><label>Sector<select value={s.sector} onChange={e=>s.set("sector",e.target.value)}><option>ALL</option>{sectors.map(x=><option key={x}>{x}</option>)}</select></label><label>Performance<select value={s.sign} onChange={e=>s.set("sign",e.target.value as any)}><option>ALL</option><option>POSITIVE</option><option>NEGATIVE</option></select></label><label className="toggle"><span>Private AI companies<small>Excluded from public totals</small></span><input type="checkbox" checked={s.showPrivate} onChange={e=>s.set("showPrivate",e.target.checked)}/></label><button className="reset" onClick={()=>{s.set("search","");s.set("country","ALL");s.set("sector","ALL");s.set("sign","ALL")}}><RotateCcw/> Reset filters</button></motion.aside>}</AnimatePresence>}
function SettingsPanel(){const s=useMarketWarStore();return <AnimatePresence>{s.settingsOpen&&<><motion.button className="scrim" aria-label="Close settings" onClick={()=>s.set("settingsOpen",false)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/><motion.aside className="drawer settings glass" initial={{x:420}} animate={{x:0}} exit={{x:420}}><div className="drawer-head"><div><small>EXPERIENCE</small><h2>Settings</h2></div><button onClick={()=>s.set("settingsOpen",false)}><X/></button></div>{[["Particle effects","particles"],["Dynamic shadows","shadows"],["Company labels","labels"],["Cinematic camera","autoCamera"],["Reduced motion","reducedMotion"]].map(([label,key])=><label className="toggle" key={key}><span>{label}</span><input type="checkbox" checked={Boolean(s[key as keyof typeof s])} onChange={e=>s.set(key as any,e.target.checked)}/></label>)}<label>Visual quality<select value={s.quality} onChange={e=>s.set("quality",e.target.value as any)}><option value="high">High detail</option><option value="low">Performance</option></select></label><div className="sound"><VolumeX/><div><b>Sound muted</b><small>Audio is off by default</small></div></div></motion.aside></>}</AnimatePresence>}
function CompanyDetails({company,total}:{company?:CompanyMarketData;total:number}){const {range,set}=useMarketWarStore();const history=useQuery({queryKey:["history",company?.id,range],queryFn:async()=>company?provider.getHistoricalData(company.id,range):[],enabled:Boolean(company)});return <AnimatePresence>{company&&<motion.aside className="details glass" initial={{x:420,opacity:0}} animate={{x:0,opacity:1}} exit={{x:420,opacity:0}}><button className="close" onClick={()=>set("selectedId",undefined)} aria-label="Close details"><X/></button><small>{company.country} · {company.exchange??"PRIVATE"}</small><h2>{company.name}</h2><p className="ticker">{company.ticker??"PRIVATE COMPANY"} <span>{company.unitType.replace("_"," ")}</span></p><div className="detail-value"><strong>{company.status==="public"?formatMarketCap(company.marketCapUsd):company.estimatedPrivateValuationUsd?formatMarketCap(company.estimatedPrivateValuationUsd):"Unranked"}</strong><b className={changeClass(performance(company,range))}>{performance(company,range)>=0?"+":""}{performance(company,range).toFixed(2)}%</b></div><p className="value-label">{company.status==="public"?"Public market capitalization":"Estimated private valuation"}</p>{company.status==="public"&&<div className="stats"><div><small>SHARE OF COUNTRY</small><b>{((company.marketCapUsd??0)/total*100).toFixed(1)}%</b></div><div><small>SECTOR</small><b>{company.sector}</b></div></div>}<div className="chart">{history.data?.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={history.data}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#62d7ad" stopOpacity={.5}/><stop offset="1" stopColor="#62d7ad" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="date" hide/><Tooltip formatter={(v:any)=>formatMarketCap(Number(v))} labelFormatter={()=>"Demo history"}/><Area type="monotone" dataKey="marketCapUsd" stroke="#62d7ad" fill="url(#area)" strokeWidth={2}/></AreaChart></ResponsiveContainer>:<span>No historical data available</span>}</div><p className="unit-explain">The <b>{company.unitType.replace("_"," ")}</b> symbolizes {company.sector?.toLowerCase()} influence. Its scale follows square-root market-cap normalization.</p><div className="detail-actions"><button onClick={()=>set("autoCamera",true)}><Focus/> Follow unit</button><button onClick={()=>set("tableOpen",true)}>Compare</button></div><footer>Updated {new Date(company.updatedAt).toLocaleString()}<br/><a href={company.sourceUrl} target="_blank" rel="noreferrer">{company.sourceName}</a></footer></motion.aside>}</AnimatePresence>}
function Timeline(){const [playing,setPlaying]=useState(false);const [value,setValue]=useState(100);useEffect(()=>{if(!playing)return;const id=setInterval(()=>setValue(v=>v>=100?0:v+1),240);return()=>clearInterval(id)},[playing]);return <div className="timeline glass"><button onClick={()=>setPlaying(!playing)} aria-label={playing?"Pause historical playback":"Play historical playback"}>{playing?<Pause/>:<Play/>}</button><div><div className="timeline-head"><span>HISTORICAL PLAYBACK</span><b>{value===100?"LIVE · JUL 2026":`${Math.round(2021+value*.05)}`}</b></div><input type="range" min="0" max="100" value={value} onChange={e=>setValue(Number(e.target.value))}/><div className="ticks"><span>5Y</span><span>1Y</span><span>1M</span><span>LIVE</span></div></div><button onClick={()=>{setValue(100);setPlaying(false)}}>Return live</button></div>}
function DataTable({companies}:{companies:CompanyMarketData[]}){const {tableOpen,set,range}=useMarketWarStore();return <AnimatePresence>{tableOpen&&<motion.section className="data-table glass" initial={{y:300}} animate={{y:0}} exit={{y:300}}><div className="drawer-head"><div><small>ACCESSIBLE ALTERNATIVE</small><h2>Company data</h2></div><button onClick={()=>set("tableOpen",false)}><X/></button></div><div className="table-scroll"><table><thead><tr><th>Company</th><th>Country</th><th>Status</th><th>Market value</th><th>{range}</th><th>Sector</th></tr></thead><tbody>{companies.map(c=><tr key={c.id}><th>{c.name} <small>{c.ticker}</small></th><td>{c.country}</td><td>{c.status}</td><td>{formatMarketCap(c.marketCapUsd??c.estimatedPrivateValuationUsd)}</td><td className={changeClass(performance(c,range))}>{performance(c,range).toFixed(2)}%</td><td>{c.sector}</td></tr>)}</tbody></table></div></motion.section>}</AnimatePresence>}

function App(){const s=useMarketWarStore();const result=useQuery({queryKey:["companies"],queryFn:async()=>{try{return await provider.getCompanies()}catch{return new MockMarketDataProvider().getCompanies()}}});const [webgl,setWebgl]=useState(true);useEffect(()=>{try{const c=document.createElement("canvas");setWebgl(Boolean(c.getContext("webgl2")||c.getContext("webgl")))}catch{setWebgl(false)}},[]);const universe=useMemo(()=>selectUniverse(result.data??[],s.count),[result.data,s.count]);const sectors=useMemo(()=>[...new Set((result.data??[]).map(c=>c.sector).filter(Boolean) as string[])].sort(),[result.data]);const filtered=useMemo(()=>{const priv=s.showPrivate?(result.data??[]).filter(c=>c.status==="private"):[];return [...universe,...priv].filter(c=>(s.country==="ALL"||c.country===s.country)&&(s.sector==="ALL"||c.sector===s.sector)&&(s.unit==="ALL"||c.unitType===s.unit)&&(s.sign==="ALL"||(s.sign==="POSITIVE"?performance(c,s.range)>=0:performance(c,s.range)<0))&&(!s.search||`${c.name} ${c.ticker}`.toLowerCase().includes(s.search.toLowerCase())))},[universe,result.data,s.showPrivate,s.country,s.sector,s.unit,s.sign,s.search,s.range]);const totals=dominance(universe);const selected=(result.data??[]).find(c=>c.id===s.selectedId);const countryTotal=selected?.country==="USA"?totals.usa:totals.china;
 if(result.isLoading)return <main className="war-app loading"><div className="loader"><span/><h1>Deploying market forces</h1><p>Validating the selected company universe…</p></div></main>;
 return <main className="war-app"><Header data={totals}/>{webgl?<SceneBoundary><Suspense fallback={<div className="webgl-fallback"><Layers3/><p>Loading strategic field…</p></div>}><MarketWarScene companies={filtered} usaPercent={totals.usaPercent}/></Suspense></SceneBoundary>:<WebGLFallback/>}<div className="field-actions"><button onClick={()=>s.set("filtersOpen",true)}><Filter/> Filters</button><button onClick={()=>s.set("tableOpen",true)}><Table2/> Data table</button></div><Legend/><Rankings companies={universe}/><Timeline/><FiltersPanel sectors={sectors}/><SettingsPanel/><CompanyDetails company={selected} total={countryTotal}/><DataTable companies={filtered}/><div className="disclaimer">Symbolic financial visualization · No real conflict depicted · Not financial advice · Market data may be delayed · Private valuations are estimates and excluded from public totals.</div></main>}
export default function MarketWarApp(){return <QueryClientProvider client={queryClient}><App/></QueryClientProvider>}
